package:
  name: pycatchmod
  version: "0.2"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy x.x
    - future
    # not actually required, but setuptools trys to pull them in otherwise
    - pandas
    - pytables
    - click
    - xlrd
    - matplotlib

  run:
    - python
    - numpy x.x
    - pandas
    - pytables
    - click
    - xlrd
    - future
    - matplotlib

test:
  imports:
    - pycatchmod
    - pycatchmod._catchmod
  commands:
    - pycatchmod version

about:
  home: https://github.com/jetuk/pycatchmod
  license: GPL v3
  summary: "A Cython implementation of the rainfall runoff model CATCHMOD (Wilby, 1994)"
